version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hapi-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hapi
      MYSQL_DATABASE: user
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - hapi-network

